version: '3'

services:
  lnp:
    container_name: lnp
    image: sebp/lighttpd:latest
    networks:
      - default
    ports:
      - "80:80"
    restart: unless-stopped
    tty: true
    volumes:
      - /root/lnp.app/build:/var/www/localhost/htdocs
      # - <config-directory>:/etc/lighttpd

networks:
  default:
    external:
      name: bridge
